---
# linux-postinstall apparmor

# TODO: disable, enforce and complain work with executables only, found by
# *which*. Enable other profiles.

- name: "apparmor: Install packages"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ lp_apparmor_packages }}"
  when:
    - lp_apparmor
    - ansible_os_family == "Debian"
  tags: lp_apparmor_packages

- include_tasks: apparmor-disable.yml
  loop: "{{ lp_apparmor_disable }}"
  tags: lp_apparmor_disable

- meta: flush_handlers
  tags: lp_apparmor_disable

- include_tasks: apparmor-enforce.yml
  loop: "{{ lp_apparmor_enforce }}"
  tags: lp_apparmor_enforce

- meta: flush_handlers
  tags: lp_apparmor_enforce

- include_tasks: apparmor-complain.yml
  loop: "{{ lp_apparmor_complain }}"
  tags: lp_apparmor_complain

- name: "apparmor: Start and enable apparmor"
  service:
    name: apparmor
    state: started
    enabled: yes
  when: lp_apparmor
  tags: lp_apparmor_service

- name: "apparmor: Stop and disable apparmor"
  service:
    name: apparmor
    state: stopped
    enabled: no
  when: not lp_apparmor
  tags: lp_apparmor_service

# EOF
...
