---
# linux-postinstall apparmor

# TODO: disable, enforce and complain work with executables only, found by
# *which*. Enable other profiles.

- name: "apparmor: Install packages"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_apparmor_packages }}"
  tags: lp_apparmor_packages

- include_tasks: apparmor-disable.yml
  loop: "{{ lp_apparmor_disable }}"
  tags: lp_apparmor_disable

# flush_handlers task does not support when conditional
# - meta: flush_handlers
#  tags: lp_apparmor_disable

- include_tasks: apparmor-enforce.yml
  loop: "{{ lp_apparmor_enforce }}"
  tags: lp_apparmor_enforce

# flush_handlers task does not support when conditional
# - meta: flush_handlers
#  tags: lp_apparmor_enforce

- include_tasks: apparmor-complain.yml
  loop: "{{ lp_apparmor_complain }}"
  tags: lp_apparmor_complain

- name: "apparmor: Start and enable apparmor"
  service:
    name: apparmor
    state: started
    enabled: yes
  when: lp_apparmor|bool
  tags: lp_apparmor_service

- name: "apparmor: Stop and disable apparmor"
  service:
    name: apparmor
    state: stopped
    enabled: no
  when: not lp_apparmor|bool
  tags: lp_apparmor_service

# EOF
...
