---
# linux-postinstall bluetooth

- name: "bluetooth: Debug"
   debug:
    msg: "lp_bluetooth [ {{ lp_bluetooth }} ]"
  when: lp_debug

- name: "bluetooth: Configure /etc/bluetooth/main.conf"
  lineinfile:
    dest: "/etc/bluetooth/main.conf"
    regexp: "^{{ item.key }}"
    insertbefore: "^{{ '#' }}{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_bluetooth_main_conf }}"
  notify: restart bluetooth

- name: "bluetooth: Enable and start bluetooth"
  systemd:
    name: "bluetooth"
    enabled: yes
    state: started
  when: lp_bluetooth

- name: "bluetooth: Stop and disable bluetooth"
  systemd:
    name: "bluetooth"
    enabled: no
    state: stopped
  when: not lp_bluetooth

# EOF
...
