---
# linux-postinstall gpsd

- name: "gpsd: Install packages for gpsd"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_gpsd_packages }}"
  tags: lp_gpsd_packages

- name: "gpsd: Add user gpsd to group dialout"
  user:
    name: "gpsd"
    groups: "dialout"
    append: yes
  tags: lp_gpsd_group

- name: "gpsd: Configure /etc/bluetooth/rfcomm.conf"
  blockinfile:
    dest: "/etc/bluetooth/rfcomm.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK rfcomm{{ item.rfcomm }}"
    insertafter: "EOF"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "{{ lp_backup_conf }}"
    block: |
      rfcomm{{ item.rfcomm }} {
        bind {{ item.bind }}
        device {{ item.device }}
        channel {{ item.channel }}
        comment "{{ item.comment }}"
        }
  loop: "{{ lp_gpsd_bt_rfcomm }}"
  notify: restart bluetooth
  tags: lp_gpsd_bt_rfcom

- name: "gpsd: Configure /etc/default/gpsd"
  template:
    src: "gpsd.j2"
    dest: "/etc/default/gpsd"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "{{ lp_backup_conf }}"
  notify: restart gpsd
  tags: lp_gpsd_config

- name: "gpsd: Stop and disable gpsd"
  systemd:
    name: "gpsd"
    state: "stopped"
    enabled: no
  when: not lp_gpsd
  tags: lp_gpsd_stop

- name: "gpsd: Start and enable gpsd"
  systemd:
    name: "gpsd"
    state: "started"
    enabled: yes
  when: lp_gpsd
  tags: lp_gpsd_start

# EOF
...
