---
# linux-postinstall lid

- name: "lid: Configure {{ lp_lid_logind_conf }}"
  lineinfile:
    dest: "{{ lp_lid_logind_conf }}"
    regexp: "^{{ item.var }}"
    line: "{{ item.var }}={{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_lid_logind_conf_vars }}"
  notify: logind message reboot

- name: "lid: Configure {{ lp_lid_upower_conf }}"
  lineinfile:
    dest: "{{ lp_lid_upower_conf }}"
    regexp: "^{{ item.var }}"
    line: "{{ item.var }}={{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_lid_upower_conf_vars }}"

# EOF
...
