---
# linux-postinstall logrotate

- name: "logrotate: Install packages for logrotate"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_logrotate_packages }}"

- name: "logrotate: Configure blocks in {{ lp_logrotate_conf_file }}"
  blockinfile:
    path: "{{ lp_logrotate_conf_file }}"
    mark: "{{ item.mark }}"
    block: "{{ item.block }}"
    state: "{{ item.state }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_logrotate_conf_blocks }}"

- name: "logrotate: Configure lines in {{ lp_logrotate_conf_file }}"
  lineinfile:
    path: "{{ lp_logrotate_conf_file }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_logrotate_conf_lines }}"

- name: "logrotate: Configure {{ lp_logrotate_conf_dir }}"
  blockinfile:
    path: "{{ lp_logrotate_conf_dir }}/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_logrotate_confd }}"

# EOF
...
