---
# linux-postinstall modules

- debug:
    msg: "lp_modules_conf [ {{ lp_modules_conf }} ]"
  when: lp_debug

- name: "modules: modprobe modules"
  modprobe:
    name: "{{ item.name }}"
    params: "{{ item.params }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ lp_modules }}"

- name: "modules: Configure {{ lp_modules_conf }} in Debian"
  lineinfile:
    dest: "{{ lp_modules_conf }}"
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} {{ item.params }}"
    backup: yes
  loop: "{{ lp_modules }}"
  when:
    - ansible_os_family == "Debian"
    - item.state | default("present") == "present"

- name: "modules: Configure {{ lp_modules_conf }} in RedHat"
  lineinfile:
    dest: "{{ lp_modules_conf }}"
    regexp: "^modprobe {{ item.name }}"
    line: "modprobe {{ item.name }} {{ item.params }}"
    backup: yes
  loop: "{{ lp_modules }}"
  when:
    - ansible_os_family == "RedHat"
    - item.state | default("present") == "present"

- name: "modules: Blacklist modules in {{ lp_modules_blacklist_path }}"
  template:
    src: blacklist-module.j2
    dest: "{{ lp_modules_blacklist_path }}/blacklist-{{ item }}.conf"
  loop: "{{ lp_modules_blacklist }}"
  notify: update initramfs

# EOF
...
