---
# linux-postinstall nfsd

- name: "nfsd: Configure exports"
  template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: reload nfsd

- name: "nfsd: Enable and start nfsd services"
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: "started"
  loop: "{{ lp_nfsd_services }}"
  when:
    - lp_nfsd
    - lp_nfsd_services > 0

- name: "nfsd: Stop and disable nfsd services"
  systemd:
    name: "{{ item }}"
    enabled: no
    state: "stopped"
  loop: "{{ lp_nfsd_services }}"
  when:
    - not lp_nfsd
    - lp_nfsd_services > 0

# EOF
...
