---
# linux-postinstall postfix

- name: "postfix: Configure /etc/postfix/main.cf"
  lineinfile:
    dest: "/etc/postfix/main.cf"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    create: yes
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_postfix_main_conf }}"
  notify: reload postfix
  tags: lp_postfix_conf

- name: "postfix: Enable and start postfix"
  systemd:
    name: "{{ lp_postfix_service }}"
    enabled: yes
    state: started
  when: lp_postfix_enable
  tags: lp_postfix_service

- name: "postfix: Disable and stop postfix"
  systemd:
    name: "{{ lp_postfix_service }}"
    enabled: no
    state: stopped
  when: not lp_postfix_enable
  tags: lp_postfix_service

# EOF
...
