---
# linux-postinstall repos

- name: "repos: Debug"
  vars:
    msg: |
      lp_repos_keys_url
      {{ lp_repos_keys_url | to_nice_yaml }}
      lp_repos_keys_id
      {{ lp_repos_keys_id | to_nice_yaml }}
      lp_repos
      {{ lp_repos | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug

- name: "repos: Add repo signing keys by URL"
  apt_key:
    url: "{{ item }}"
  loop: "{{ lp_repos_keys_url }}"
  register: result
  retries: "{{ lp_install_retries }}"
  until: result is succeeded
  delay: "{{ lp_install_delay }}"
  tags: lp_repos_keys_add

- name: "repos: Add repo signing keys by ID"
  apt_key:
    id: "{{ item.id }}"
    keyserver: "{{ item.keyserver }}"
    state: "present"
  loop: "{{ lp_repos_keys_id }}"
  register: result
  retries: "{{ lp_install_retries }}"
  until: result is succeeded
  delay: "{{ lp_install_delay }}"
  tags: lp_repos_keys_add

- name: "repos: Add repositories"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  loop: "{{ lp_repos }}"
  tags: lp_repos_add

# EOF
...
