---

- name: "service: Manage services."
  service:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    arguments: "{{ item.arguments | default(omit) }}"
    pattern: "{{ item.pattern | default(omit) }}"
    runlevel: "{{ item.runlevel | default(omit) }}"
    sleep: "{{ item.sleep | default(omit) }}"
    use: "{{ item.use | default('auto') }}"
  loop: "{{ lp_service }}"
  when: (item.state is defined) or
        (item.enabled is defined)

# EOF
...
