---
# linux-postinstall smart

- name: "smart: Install packages"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_smart_packages }}"
  when: lp_smart
  tags: lp_smart_packages

- name: "smart: Configure {{ lp_smart_conf_file }}. Do not scan for devices"
  lineinfile:
    state: absent
    dest: "{{ lp_smart_conf_file }}"
    regexp: "^DEVICESCAN"
    owner: "{{ lp_smart_conf_owner }}"
    group: "{{ lp_smart_conf_group }}"
    mode: "{{ lp_smart_conf_mode }}"
    create: yes
    backup: yes
  when: not lp_smart_devicescan
  notify: reload smart
  tags: lp_smart_conf

- name: "smart: Configure devices in {{ lp_smart_conf_file }}"
  lineinfile:
    dest: "{{ lp_smart_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ lp_smart_conf_owner }}"
    group: "{{ lp_smart_conf_group }}"
    mode: "{{ lp_smart_conf_mode }}"
    create: yes
    backup: yes
  loop: "{{ lp_smart_devices }}"
  notify: reload smart
  tags: lp_smart_conf

- name: "smart: Start and enable smart"
  service:
    name: "{{ lp_smart_service_name }}"
    state: started
    enabled: yes
  when: lp_smart
  tags: lp_smart_service

- name: "smart: Stop and disable smart"
  service:
    name: "{{ lp_smart_service_name }}"
    state: stopped
    enabled: no
  when: not lp_smart
  tags: lp_smart_service

# EOF
...
