---
# linux-postinstall sshd

- name: "sshd: Configure /etc/ssh/sshd_config"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^{{ item.key }}"
    insertbefore: "^{{ '#' }}{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
    validate: "{{ lp_path_sshd }} -t -f %s"
  loop: "{{ lp_sshd_config }}"
  notify: reload sshd

- name: "sshd: Enable and start sshd"
  systemd:
    name: "{{ lp_service_sshd }}"
    enabled: yes
    state: "started"
  when: lp_sshd

- name: "sshd: Disable and stop sshd"
  systemd:
    name: "{{ lp_service_sshd }}"
    enabled: no
    state: "stopped"
  when: not lp_sshd

# EOF
...
