---
# linux-postinstall udev

- name: "udev: Debug"
  vars:
    msg: |
      lp_udev_persistent_net_rules
      {{ lp_udev_persistent_net_rules | to_nice_yaml }}
      lp_udev_hci_name_rules
      {{ lp_udev_hci_name_rules | to_nice_yaml }}
      lp_udev_hci_run_rules
      {{ lp_udev_hci_run_rules | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug

# persistent_net
- name: "udev: Configure {{ lp_udev_rules_dir }}/
                         {{ lp_udev_persistent_net_rules_file }}"
  template:
    src: "persistent-net.rules.j2"
    dest: "{{ lp_udev_rules_dir }}/{{ lp_udev_persistent_net_rules_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_udev_persistent_net_rules }}"
  notify: reload udev

# hci name
- name: "udev: Configure {{ lp_udev_rules_dir }}/
                         {{ lp_udev_hci_name_rules_file }}"
  template:
    src: "hci-name.rules.j2"
    dest: "{{ lp_udev_rules_dir }}/{{ lp_udev_hci_name_rules_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_udev_hci_name_rules }}"
  notify: reload udev

# hci run
- name: "udev: Configure {{ lp_udev_rules_dir }}/
                         {{ lp_udev_hci_run_rules_file }}"
  template:
    src: "hci-run.rules.j2"
    dest: "{{ lp_udev_rules_dir }}/{{ lp_udev_hci_run_rules_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_udev_hci_run_rules }}"
  notify: reload udev

# EOF
...
