---
# linux-postinstall wpa_gui
# Install wpa_gui and disable NetworkManager

- name: "wpagui: Debug"
  vars:
    msg: |
      lp_wpagui_packages
      {{ lp_wpagui_packages | to_nice_yaml }}
      lp_wpagui_systemd
      {{ lp_wpagui_systemd | to_nice_yaml }}
      lp_wpagui_service
      {{ lp_wpagui_service | to_nice_yaml }}
      lp_wpagui_service_mask
      {{ lp_wpagui_service_mask | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug

- name: "wpagui: Install packages"
  package:
    name: "{{ item }}"
    state: "{{ lp_package_state }}"
  loop: "{{ lp_wpagui_packages }}"
  tags: lp_wpagui_packages

- name: "wpagui: Disable NM /etc/init/network-manager.override"
  template:
    src: "network-manager-override.j2"
    dest: "/etc/init/network-manager.override"
    owner: "root"
    group: "root"
    mode: "0644"
  tags: lp_wpagui_disableNM

- name: "wpagui: Configure managed=false
                 in /etc/NetworkManager/NetworkManager.conf"
  lineinfile:
    dest: "/etc/NetworkManager/NetworkManager.conf"
    regexp: "^managed"
    line: "managed=false"
  tags: lp_wpagui_disableNM

# NetworkManager.service will be stopped and disabled in the next task
# - name: "wpagui: Stop and disable NM"
#  systemd:
#    name: "{{ item }}"
#    state: "stopped"
#    enabled: no
#  loop: "{{ lp_wpagui_systemd }}"
#  tags: lp_wpagui_disableNM

- name: "wpagui: Stop and disable all NM services"
  service:
    name: "{{ item }}"
    state: "stopped"
    enabled: no
  loop: "{{ lp_wpagui_service }}"
  tags: lp_wpagui_disableNM

- name: "wpagui: Mask NM services"
  command: "systemctl mask {{ item }}"
  loop: "{{ lp_wpagui_service_mask }}"
  changed_when: false
  tags: lp_wpagui_mask_NM

# EOF
...
