---
# linux-postinstall xen

- name: "xen: Debug"
  vars:
    msg: |
      lp_xen_packages
      {{ lp_xen_packages | to_nice_yaml }}
      lp_xen_dom0_mem
      {{ lp_xen_dom0_mem | to_nice_yaml }}
      lp_xen_global
      {{ lp_xen_global | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug|bool

- name: "xen: Install packages"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_xen_packages }}"
  tags: lp_xen_packages

- name: "xen: Configure GRUB_CMDLINE_XEN_DEFAULT in /etc/default/grub"
  lineinfile:
    dest: "/etc/default/grub"
    regexp: "^\\s*GRUB_CMDLINE_XEN_DEFAULT\\s*="
    line: "GRUB_CMDLINE_XEN_DEFAULT=\"dom0_mem={{ lp_xen_dom0_mem }},
                                      max:{{ lp_xen_dom0_mem_max }}\""
    backup: "{{ lp_backup_conf }}"
  notify: update grub
  tags: lp_xen_grub

- name: "xen: Configure XEN_OVERRIDE_GRUB_DEFAULT in /etc/default/grub"
  lineinfile:
    dest: "/etc/default/grub"
    regexp: "^\\s*XEN_OVERRIDE_GRUB_DEFAULT\\s*="
    line: "XEN_OVERRIDE_GRUB_DEFAULT={{ lp_xen_XEN_OVERRIDE_GRUB_DEFAULT }}"
    backup: "{{ lp_backup_conf }}"
  notify: update grub
  tags: lp_xen_grub

- name: "xen: Configure /etc/xen/xl.conf"
  lineinfile:
    dest: "/etc/xen/xl.conf"
    regexp: "^\\s*{{ item.var }}\\s*="
    line: "{{ item.var }}={{ item.value }}"
    create: yes
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_xen_global }}"
  when: lp_xen_global > 0
  tags: lp_xen_global

# EOF
...
