---
# linux-postinstall handlers

- name: restart timesyncd
  service: name="systemd-timesyncd.service" state="restarted"

- name: load sysctl settings
  command: "/sbin/sysctl -p /etc/sysctl.conf"

- name: reload iptables
  shell: "/sbin/iptables-restore < /etc/network/iptables"

- name: newaliases
  command: newaliases

- name: set hostname
  command: "/sbin/sysctl kernel.hostname={{ hostname }}"

- name: update grub
  command: "/usr/sbin/update-grub"

- name: reload udev
  command: "/sbin/udevadm control --reload-rules"
#  Ubuntu 18.04 error: Failed to reload udev.service: Job type reload
#  is not applicable for unit systemd-udevd.service
#  systemd: name="udev" state="reloaded"

- name: restart udev
  systemd: name="udev" state="restarted"

- name: reload sshd
  systemd: name="{{ lp_service_sshd }}" state="reloaded"
  when: lp_sshd

- name: restart bluetooth
  systemd: name="bluetooth" state="restarted"
  when: lp_bluetooth

- name: restart gpsd
  systemd: name="gpsd" state="restarted"
  when: lp_gpsd

- name: restart postfix
  systemd: name="postfix" state="restarted"
  when: lp_postfix

- name: reload postfix
  systemd: name="postfix" state="reloaded"
  when: lp_postfix

- name: reload smart
  systemd: name="{{ lp_smart_service_name }}" state="reloaded"
  when: lp_smart

- name: apparmor disable profile
  shell: apparmor_parser -R /etc/apparmor.d/"{{ apparmor_item_path.stdout }}"

- name: apparmor enforce profile
  shell: apparmor_parser -r /etc/apparmor.d/"{{ apparmor_item_path.stdout }}"

- name: reload nfsd
  systemd: name="{{ lp_nfsd_reload_service }}" state="reloaded"
  when: lp_nfsd

- name: netplan apply
  shell: netplan apply
  when: lp_netplan

- name: create and mount swap file
  shell: sh -c 'dd if=/dev/zero of={{ lp_swap_file }} bs=1M count={{ lp_swap_size }} && chmod 0600 {{ lp_swap_file }} && mkswap {{ lp_swap_file }} && swapon {{ lp_swap_file }}'

- name: change and mount swap file
  shell: sh -c 'swapoff {{ lp_swap_file }} && dd if=/dev/zero of={{ lp_swap_file }} bs=1M count={{ lp_swap_size }} && chmod 0600 {{ lp_swap_file }} && mkswap {{ lp_swap_file }} && swapon {{ lp_swap_file }}'

- name: remove swap file
  shell: sh -c 'swapoff {{ lp_swap_file }} && rm {{ lp_swap_file }}'

- name: restart tlp
  systemd: name="{{ lp_tlp_restart_service }}" state="restarted"
  when: lp_tlp_enable

- name: restart autofs
  systemd: name="autofs" state="restarted"
  when: lp_autofs_enable

- name: reload autofs
  systemd: name="autofs" state="reloaded"
  when: lp_autofs_enable

- name: update initramfs
  command: update-initramfs -u

- name: restart libvirtd
  systemd: name="{{ lp_libvirt_libvirtd_service }}" state="restarted"
  when: lp_libvirt_libvirtd_enable

- name: reload libvirtd
  systemd: name="{{ lp_libvirt_libvirtd_service }}" state="reloaded"
  when: lp_libvirt_libvirtd_enable

- name: restart libvirt_guests
  systemd: name="{{ lp_libvirt_guests_service }}" state="restarted"
  when: lp_libvirt_libvirtd_enable

- name: reload libvirt_guests
  systemd: name="{{ lp_libvirt_guests_service }}" state="reloaded"
  when: lp_libvirt_libvirtd_enable

# MESSAGES -------------------------------------------------------------
- name: logind message reboot
  debug: msg="[MESSAGE] Reboot to activate configuration in logind.conf"

# EOF
...
