---
# linux-postinstall function install-package

- name: "fn install-package: {{ lp_package_state }} package: {{ item }}"
  package:
    name: "{{ item }}"
    state: "{{ lp_package_state }}"
  register: result
  retries: "{{ lp_install_retries }}"
  until: result is succeeded
  delay: "{{ lp_install_delay }}"
  when: not lp_package_install_dryrun|bool
  tags: lp_packages_auto

# EOF
...
